name: NodeJS with Gulp (Backend + Frontend)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Install Frontend Dependencies (Frontend is at Root)
    - name: Install Frontend Dependencies
      run: npm install

    - name: Build Frontend (Gulp)
      run: gulp

    # Install Backend Dependencies
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Start Backend Server
      run: |
        cd backend
        npm run start &  # Run backend in the background

    - name: Connect Frontend to Backend
      run: |
        echo "REACT_APP_BACKEND_URL=http://localhost:5000" > .env  # Set backend URL for frontend
